### ISSUE TITLE
needs iphone 6 11.2.1 offsets

### ISSUE THREAD

**Issue by thealphawerewolf** [MTJailed/PurpleSmoke#4]
can u add 11.2.1 offsets iphone 6

**Comment by Dave1482** [comment]
I believe he would need that kind of device to actually get them. Try installing this through xCode or use the already compiled app with iOS App Signer or Cydia Impactor at https://github.com/MTJailed/PurpleSmoke/releases and get a screenshot. Attached is a cropped screenshot from when I ran it on my device. I used a version modified with a bit of my code to get all of them.
![img_2138_01](https://user-images.githubusercontent.com/3741780/40279375-36e8c49c-5c07-11e8-90f3-0a4f4cb1c1b3.png)

**Comment by thealphawerewolf** [comment]
ok thnx

**Comment by MTJailed** [comment]
lel0_async_vector_long is the same as the leaked value because that is what the value leaks, you can just remove it.

As for finding the offsets it is as easy as running this project and taking note of the kernel text base in the panic log and the leaked pointer in the output.

You can code your offset support in offsets file :)
